
import React from 'react';
import { 
  Fingerprint, IdCard, Briefcase, HeartPulse, Sprout, Vote, Book, 
  Wallet, ShieldCheck, PieChart, Monitor, GraduationCap, Brain, 
  Zap, TrainFront, Car, FileBadge, IndianRupee, Home, Baby, 
  Accessibility, Heart, Map, HardHat, Users, UserCheck, PiggyBank, 
  Building2, Gauge, BarChart, Settings, DraftingCompass, Store, 
  Leaf, Mountain, Sun, Umbrella, Bus, Plane, Receipt, Info, 
  AlertTriangle, Gavel, Banknote, FileText, Cloud, FileStack
} from 'lucide-react';
import { Service, Category } from './types';

export const CATEGORIES: Category[] = [
  { code: 'G2C', title: 'सरकारी सेवाएं (G2C)', description: 'Government to Citizen Services' },
  { code: 'Bank', title: 'बैंकिंग और बीमा', description: 'Banking, Insurance & Pension' },
  { code: 'Edu', title: 'शिक्षा और कौशल', description: 'Education & Skill Development' },
  { code: 'Util', title: 'यूटिलिटी बिल एवं यात्रा', description: 'Utility Payments & Travel' },
];

export const ALL_SERVICES: Service[] = [
  // G2C - सरकारी सेवाएँ
  { name: "आधार डाउनलोड", cat: "G2C", url: "https://uidai.gov.in", iconName: "Fingerprint" },
  { name: "पैन कार्ड", cat: "G2C", url: "https://www.onlineservices.nsdl.com", iconName: "IdCard" },
  { name: "ई-श्रम रजिस्ट्रेशन", cat: "G2C", url: "https://eshram.gov.in", iconName: "Briefcase" },
  { name: "आयुष्मान कार्ड", cat: "G2C", url: "https://bis.pmjay.gov.in", iconName: "HeartPulse" },
  { name: "PM किसान", cat: "G2C", url: "https://pmkisan.gov.in", iconName: "Sprout" },
  { name: "वोटर सर्विस", cat: "G2C", url: "https://voters.eci.gov.in", iconName: "Vote" },
  { name: "पासपोर्ट सेवा", cat: "G2C", url: "https://www.passportindia.gov.in", iconName: "Book" },
  { name: "जाति प्रमाण पत्र", cat: "G2C", url: "https://edistrict.up.gov.in", iconName: "FileBadge" },
  { name: "आय प्रमाण पत्र", cat: "G2C", url: "https://edistrict.up.gov.in", iconName: "IndianRupee" },
  { name: "निवास प्रमाण पत्र", cat: "G2C", url: "https://edistrict.up.gov.in", iconName: "Home" },
  { name: "जन्म प्रमाण पत्र", cat: "G2C", url: "https://crsorgi.gov.in", iconName: "Baby" },
  { name: "दिव्यांग प्रमाण पत्र", cat: "G2C", url: "https://www.swavlambancard.gov.in", iconName: "Accessibility" },
  { name: "शादी अनुदान", cat: "G2C", url: "https://shadianudan.upsdc.gov.in", iconName: "Heart" },
  { name: "खतौनी (भूलेख)", cat: "G2C", url: "https://upbhulekh.gov.in", iconName: "Map" },
  { name: "श्रम कार्ड नवीनीकरण", cat: "G2C", url: "https://uplabour.gov.in", iconName: "HardHat" },
  { name: "पारिवारिक लाभ", cat: "G2C", url: "https://nfbs.upsdc.gov.in", iconName: "Users" },
  { name: "ई-कोर्ट स्टेटस", cat: "G2C", url: "https://ecourts.gov.in", iconName: "Gavel" },
  { name: "डिजीलॉकर", cat: "G2C", url: "https://www.digilocker.gov.in", iconName: "Cloud" },
  { name: "उद्यम रजिस्ट्रेशन", cat: "G2C", url: "https://udyamregistration.gov.in", iconName: "Briefcase" },
  { name: "ई-नाम (Mandi)", cat: "G2C", url: "https://enam.gov.in", iconName: "Store" },
  { name: "खाद/उर्वरक लाइसेंस", cat: "G2C", url: "https://fert.nic.in", iconName: "Leaf" },
  { name: "मृदा स्वास्थ्य कार्ड", cat: "G2C", url: "https://soilhealth.dac.gov.in", iconName: "Mountain" },
  { name: "कुसुम योजना", cat: "G2C", url: "https://pmkusum.mnre.gov.in", iconName: "Sun" },
  { name: "फसल बीमा (PMFBY)", cat: "G2C", url: "https://pmfby.gov.in", iconName: "Umbrella" },

  // Banking & Insurance
  { name: "DigiPay (AEPS)", cat: "Bank", url: "https://digipay.csccloud.in", iconName: "Wallet" },
  { name: "बीमा प्रीमियम", cat: "Bank", url: "https://digitalseva.csc.gov.in/", iconName: "ShieldCheck" },
  { name: "NPS रजिस्ट्रेशन", cat: "Bank", url: "https://enps.nsdl.com", iconName: "PieChart" },
  { name: "जीवन प्रमाण", cat: "Bank", url: "https://jeevanpramaan.gov.in", iconName: "UserCheck" },
  { name: "अटल पेंशन योजना", cat: "Bank", url: "https://www.npscra.nsdl.co.in", iconName: "PiggyBank" },
  { name: "SBI नेट बैंकिंग", cat: "Bank", url: "https://www.onlinesbi.sbi", iconName: "Building2" },
  { name: "PNB नेट बैंकिंग", cat: "Bank", url: "https://www.pnbindia.in", iconName: "Building2" },
  { name: "BoB नेट बैंकिंग", cat: "Bank", url: "https://www.bankofbaroda.in", iconName: "Building2" },
  { name: "HDFC बैंकिंग", cat: "Bank", url: "https://www.hdfcbank.com", iconName: "Building2" },
  { name: "ICICI बैंकिंग", cat: "Bank", url: "https://www.icicibank.com", iconName: "Building2" },
  { name: "मुद्रा लोन", cat: "Bank", url: "https://www.mudra.org.in", iconName: "IndianRupee" },
  { name: "क्रेडिट स्कोर", cat: "Bank", url: "https://www.cibil.com", iconName: "Gauge" },
  { name: "PF (EPFO) चेक", cat: "Bank", url: "https://www.epfindia.gov.in", iconName: "Banknote" },

  // Education & Skill
  { name: "PMGDisha", cat: "Edu", url: "https://www.pmgdisha.in", iconName: "Monitor" },
  { name: "NIOS एडमिशन", cat: "Edu", url: "https://sdmis.nios.ac.in", iconName: "GraduationCap" },
  { name: "कौशल विकास", cat: "Edu", url: "https://www.skillindia.gov.in", iconName: "Brain" },
  { name: "यूपी स्कॉलरशिप", cat: "Edu", url: "https://scholarship.up.gov.in", iconName: "GraduationCap" },
  { name: "NSP छात्रवृत्ति", cat: "Edu", url: "https://scholarships.gov.in", iconName: "GraduationCap" },
  { name: "CCC एग्जाम फॉर्म", cat: "Edu", url: "https://student.nielit.gov.in", iconName: "Monitor" },
  { name: "IGNOU एडमिशन", cat: "Edu", url: "https://ignouadmission.samarth.edu.in", iconName: "Book" },
  { name: "UP बोर्ड रिजल्ट", cat: "Edu", url: "https://upresults.nic.in", iconName: "BarChart" },
  { name: "ITI एडमिशन", cat: "Edu", url: "https://scvtup.in", iconName: "Settings" },
  { name: "Polytechnic फॉर्म", cat: "Edu", url: "https://jeecup.admissions.nic.in", iconName: "DraftingCompass" },

  // Utility & B2C
  { name: "बिजली बिल", cat: "Util", url: "https://www.bbps.org.in", iconName: "Zap" },
  { name: "IRCTC टिकट", cat: "Util", url: "https://www.irctc.co.in", iconName: "TrainFront" },
  { name: "FASTag", cat: "Util", url: "https://www.fastag.org", iconName: "Car" },
  { name: "बस टिकट (UPSRTC)", cat: "Util", url: "https://www.upsrtc.com", iconName: "Bus" },
  { name: "फ्लाइट बुकिंग", cat: "Util", url: "https://www.makemytrip.com", iconName: "Plane" },
  { name: "चालान भुगतान", cat: "Util", url: "https://echallan.parivahan.gov.in", iconName: "Receipt" },
  { name: "गाड़ी का RC स्टेटस", cat: "Util", url: "https://vahan.parivahan.gov.in", iconName: "Info" },
  { name: "HSRP प्लेट", cat: "Util", url: "https://bookmyhsrp.com", iconName: "AlertTriangle" },
];

export const ICON_MAP: Record<string, React.ReactNode> = {
  Fingerprint: <Fingerprint />,
  IdCard: <IdCard />,
  Briefcase: <Briefcase />,
  HeartPulse: <HeartPulse />,
  Sprout: <Sprout />,
  Vote: <Vote />,
  Book: <Book />,
  Wallet: <Wallet />,
  ShieldCheck: <ShieldCheck />,
  PieChart: <PieChart />,
  Monitor: <Monitor />,
  GraduationCap: <GraduationCap />,
  Brain: <Brain />,
  Zap: <Zap />,
  TrainFront: <TrainFront />,
  Car: <Car />,
  FileBadge: <FileBadge />,
  IndianRupee: <IndianRupee />,
  Home: <Home />,
  Baby: <Baby />,
  Accessibility: <Accessibility />,
  Heart: <Heart />,
  Map: <Map />,
  HardHat: <HardHat />,
  Users: <Users />,
  UserCheck: <UserCheck />,
  PiggyBank: <PiggyBank />,
  Building2: <Building2 />,
  Gauge: <Gauge />,
  BarChart: <BarChart />,
  Settings: <Settings />,
  DraftingCompass: <DraftingCompass />,
  Store: <Store />,
  Leaf: <Leaf />,
  Mountain: <Mountain />,
  Sun: <Sun />,
  Umbrella: <Umbrella />,
  Bus: <Bus />,
  Plane: <Plane />,
  Receipt: <Receipt />,
  Info: <Info />,
  AlertTriangle: <AlertTriangle />,
  Gavel: <Gavel />,
  Banknote: <Banknote />,
  FileText: <FileText />,
  Cloud: <Cloud />,
  FileStack: <FileStack />
};
